import crypto from 'crypto';

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  const { payment_token, booking_data } = req.body;
  if (!payment_token || !booking_data) {
    return res.status(400).json({ message: 'Missing payment proof or booking data' });
  }

  const key_secret = process.env.RAZORPAY_KEY_SECRET;
  if (!key_secret) {
    console.error("Razorpay Key Secret missing.");
    return res.status(500).json({ message: 'Server configuration error' });
  }

  // 1. Verify Payment Token Cryptographically (Prevents bypass attacks)
  try {
    const parts = payment_token.split('.');
    if (parts.length !== 2) throw new Error('Invalid token format');
    
    const [tokenPayload, tokenSignature] = parts;
    const expectedSignature = crypto.createHmac('sha256', key_secret).update(tokenPayload).digest('base64');
    
    if (expectedSignature !== tokenSignature) {
      return res.status(403).json({ message: 'Invalid payment proof signature. Unauthorized routing.' });
    }

    const payload = JSON.parse(Buffer.from(tokenPayload, 'base64').toString('utf8'));
    
    // Check Authorization Expiration
    if (Date.now() > payload.exp) {
      return res.status(403).json({ message: 'Payment verification session expired. Please contact support.' });
    }

    // 2. Validate Secure Booking Data constraints
    const { 
      bookingId,
      full_name, 
      email, 
      phone, 
      appointmentDate, 
      appointmentStartTime, 
      appointmentEndTime, 
      duration_mins 
    } = booking_data;
    
    if (!full_name || !email || !appointmentDate || !appointmentStartTime) {
      return res.status(400).json({ message: 'Incomplete booking details provided.' });
    }

    if (duration_mins !== 15) {
      return res.status(400).json({ message: 'Only 15-minute durations are permitted for this session.' });
    }

    // 3. Assemble Excel webhook schema exactly as requested
    const POWER_AUTOMATE_WEBHOOK_URL = process.env.POWER_AUTOMATE_BOOKING_WEBHOOK_URL || process.env.VITE_POWER_AUTOMATE_BOOKING_URL;
    let automationSuccess = true;

    // Strict mapping to the Power Automate Excel Table API payload format
    const paPayload = {
      bookingId: bookingId || `ND-${Date.now()}`,
      name: full_name,
      email: email,
      phone: phone || "Unknown",
      razorpayOrderId: payload.order_id,
      razorpayPaymentId: payload.payment_id || null,
      paymentStatus: "PAYMENT_VERIFIED",
      bookingStatus: "BOOKED",
      appointmentDate: appointmentDate,
      appointmentStartTime: appointmentStartTime,
      appointmentEndTime: appointmentEndTime,
      duration: 15,
      bookingAppointmentId: null,
      teamsMeetingLink: "Will be generated by Power Automate MS Bookings Step",
      failureReason: null,
      source: "nenovoice.com",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    if (POWER_AUTOMATE_WEBHOOK_URL) {
      try {
        const automatorRes = await fetch(POWER_AUTOMATE_WEBHOOK_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(paPayload)
        });
        if (!automatorRes.ok) automationSuccess = false;
      } catch (err) {
        console.error("Backend workflow API failure:", err);
        automationSuccess = false;
      }
    } else {
      console.log(`[VERIFIED SECURE] Webhook simulated. Payload ready to send:`, paPayload);
    }

    if (!automationSuccess) {
      return res.status(500).json({ message: 'Failed to synchronize with backend calendar services. Our team is notified.' });
    }

    return res.status(200).json({ 
      success: true, 
      message: 'Booking securely verified and calendar integrated.' 
    });

  } catch (err) {
    console.error("Confirm booking orchestration error:", err);
    return res.status(500).json({ message: 'Secure booking confirmation failed', error: err.message });
  }
}
